merge 2025-09-03 (#103)
* MILAB-1632: run build-and-tests on pr branches regardless of changeset job results
* check for docker compose
* add review checker job
* checkout repo before doing checks
* report error to summary if review is required
* Make it to be pnpm monorepo (#95)
* make this repo to be pnpm monorepo with milib in separate package
* adjust test config
* feat: wf for python runenv parallel build
* feat: run docker compose with cli options
* feat: send notifications to slack
* feat: jinja-js action
* feat(jinja-js): Add compiled dist for JS action
* fix: gitignore
* fix: small thiings
* fix: errors
* refactor(jinja-js): Safely handle github context
* fix: Error: Cannot find module '@actions/core'
* fix: head commit
* feat: create new slack notify action as a replacment for telegram actions
* fix: publish slack tempalte
* fix: templating error
* fix: test templating
* feat: add slack notifications to monorepo workflow
* disable ECR login for quay and containers.pl-open.science
* fail CI when pnpm-workspace gets updated without lock
* drop postbuild-publish hack
* drop 'build-descriptors' call
* bring publish-archive to pre-calculated build step
* rename prebuild step
* put 'if-present' to correct place
* bring before-publish step back :(
* correct artifact name
* correct restore artifact pattern
* rename job

---------

Co-authored-by: Vladimir Antropov <vladimir.antropov@milaboratories.com>
Co-authored-by: MavisNo11 <osudarev@milaboratories.com>